### ISSUE TITLE
[HZN-105] Fit T2 relaxometry model with Rician PDF

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#104]
Transferred by @LaurenceJackson on Apr 23, 2021, 16:56

:::Issue recreated from Jira issue [HZN-105](https://gsttmri.atlassian.net/browse/HZN-105):::

The current relaxometry method assumes Gaussian noise distribution. For  magnitude images a Rician distribution is a better description of the signal with the incorporation of noise. The current assumption of Gaussian noise leads to inaccurate fitting for samples where the SNR is low, roughly when the \[maximum TE] > 4*T2.

A possible method to correct is found in Raya et al [https://doi.org/10.1002/mrm.22178|https://doi.org/10.1002/mrm.22178|smart-link]

**Comment by Lucrezia-Cester** [comment]
Hi @pcw24601, will you work on this PR? I could do this myself otherwise

**Comment by pcw24601** [comment]
Hi @Lucrezia-Cester. I'm keen to work on this as it seems like a fun challenge, but I haven't had much time over the past few months and I don't know when that will change! So feel free to attack it if it interests you (and we could maybe collaborate later on).

I struggled to figure out what to do but now have two possible lines of attack--a maximum likelihood estimation (MLE) method and a loss function approach. Have you any experience of modelling Rician noise? Any thoughts on which way to go?

Option 1:
![image](https://user-images.githubusercontent.com/87647715/143466266-3c0493a0-79db-49f2-9905-77266dd7af66.png)
Option 2:
![image](https://user-images.githubusercontent.com/87647715/143466333-a3126180-b4aa-4952-ab5c-346d7bd1de5a.png)

Refs:
Raya, J.G., Dietrich, O., Horng, A., Weber, J., Reiser, M.F. and Glaser, C., 2010. T2 measurement in articular cartilage: impact of the fitting method on accuracy and precision at low SNR. Magnetic Resonance in Medicine: An Official Journal of the International Society for Magnetic Resonance in Medicine, 63(1), pp.181-193.

Bouhrara, M., Reiter, D.A., Celik, H., Bonny, J.M., Lukas, V., Fishbein, K.W. and Spencer, R.G., 2015. Incorporation of Rician noise in the analysis of biexponential transverse relaxation in cartilage using a multiple gradient echo sequence at 3 and 7 Tesla. Magnetic resonance in medicine, 73(1), pp.352-366.

Cárdenas‐Blanco, A., Tejos, C., Irarrazaval, P. and Cameron, I., 2008. Noise in magnitude magnetic resonance images. Concepts in Magnetic Resonance Part A: An Educational Journal, 32(6), pp.409-416.

**Comment by Lucrezia-Cester** [comment]
Hi @pcw24601, happy to collaborate on this. I am not 100% sure how to solve this but I thought I'd give it a try. 

So from what I gathered MRI images present Rician noise if only the magnitude part of the image is extrapolated. 

For the relaxometry Hazen module, If the input image in an MRI, why are we trying to add Rician nosise? The image will already have it.

If instead we are not working with a magnitude image then we don't have Rician noise and this can be extracted by subtracting the magnitude phase image from the magnitude image. 

I guess what I am trying to get at is this: why do we want do add Rician noise?

**Comment by tomaroberts** [comment]
Hi both,

Have done a bit of reading up on this. This link gives a nice overview of noise in MR data: https://mriquestions.com/signal-to-noise.html

It also links to three very handy NEMA documents in the references at the bottom. 

Rician/Rayleigh effects can be corrected for by multiplying an SNR measurement (i.e.: a naive measurement that assumes your data has Gaussian noise) by a bias correction factor. For a single-coil acquisition, this factor = 0.66. So: SNR_true = 0.66 * SNR_measured.

[The exact maths behind the 0.66 is not entirely clear to me... but it's to do with noise probability distributions]

The link above also discusses how noise properties change when acquiring multicoil data. In fact, NEMA provides a lookup table which allows you too apply the correct bias correction factor depending on how many coils you used: https://mriquestions.com/uploads/3/4/5/7/34572113/nema_ms_9-2008_r2014.pdf

Do we use a multi-channel coil for our phantom QA measurements? If so, it might be possible to extract the number of coils used in the acquisition from the DICOM header and use this to inform the bias correction factor.

**Comment by pcw24601** [comment]
Hi @Lucrezia-Cester,

This problem has been one of those itches in the back of my mind for probably two years, and I've struggled to get the maths to deal with it. Looking back at my original log of the problem, I must apologise for not really describing the issue. I'll have another go in order to clarify the issue for other devs.

The problem is for T2 relaxometery measurements on species with a short T2. The data are typically acquired using a dedicated 32 echo sequence--one 90 degree pulse, followed by a chain of 180 deg refocussing pulses, to produce 32 images with gradually increasing TE. The idea is then to fit a decay curve:
<img src="https://render.githubusercontent.com/render/math?math=S(\mathrm{TE})=S_0 e^\left({\frac{\mathrm{-TE}}{T_2}}\right)">
and solve for S0 and TE, either on a pixel-by-pixel basis, or (as in the current Hazen implementation) over an ROI.

There are a few problems (apologies, I don't have the references to hand):
1. The first echo is disproportionately low. If I recall, this is due to subsequent echoes actually being too high due to a stimulated echo component. Our group (and the Hazen implementation) omit the first echo and process the remaining 31.
2. Odd echoes are slightly too low due to B1 imperfections (i.e. not exactly a 180 deg refocussing pulse). We ignore this. Taking only even pulses will likely give a better fit if there is a lot of data, but you end up throwing away too many data points for species which decay quickly (short T2).
3. Rician noise. We can picture the measured signal Sm as the actual signal S plus some N. If the noise follows a Gaussian distribution (as is reasonable to assume in the measured signal), then N should average to zero. This is implicitly assumed in most fitting algorithms--they minimise the difference between the measured values Sm and the model output, and assume that the model is fitted when the mean squared difference is smallest. However, most MR images, including those acquired by default in T2 mapping, only produce a magnitude reconstruction. (It's possible to get phase images too, or real/imaginary, or a signed image which I think  Siemens scanners call 'real'. These will remove this problem but may cause others.) For magnitude reconstructions, the noise becomes Rician distributed and trying to fit using algorithms which assume a Gaussian distribution (e.g. minimising mean squared error) will not produce a good result. E.g. if the last four points in a time series are [-5, 3, 6, -4] they are likely at TE >> T2 (i.e. just noise, but the signal has decayed to zero). However, in the magnitude reconstruction, they become [5, 3, 6, 4] and an off-the-shelf fitting algorithm, which attempts to minimise MSE, won't find the best fit.

There are a few ways to deal with this, such as adding a constant to the model, or truncating the data once it gets too low, but correctly dealing with the noise model would be best.

The two slides pasted above are my attempts to correctly model Rician noise, based on the papers referenced. In either attempt, there is an function to minimise. E.g. in Option 1, get ROI values (*y* vector) at various *TE*s and estimate s.d. of noise (sigma) from your images. Plug these values into a solver to search for T2, S0 to maximise the expression (or minimise its negative if easier).

My maths isn't good enough to know if this is the best way to go (comments welcome!) but I think it's worth a try.

**Comment by pcw24601** [comment]
@tomaroberts , I posted the above comment prior to seeing yours--sorry. It's been a while since I had a look at the NEMA docs, but I don't think our issue here is correcting an SNR measurement, it's how do we get the best fit for an exponential decay when the data trend to a noise valve, rather than zero?

For the simulated data below, the dots are points drawn from data following the blue line, with Rician noise added--everything looks good at high signal, but not when signal is low. What's the best way to get the blue line from the dots?
![image](https://user-images.githubusercontent.com/87647715/143881029-8afa2b58-5125-490c-b8b0-2e49a1feeed0.png)

**Comment by tomaroberts** [comment]
Ahh, sorry Paul – you are right. I've been reading too many different hazen issues today and got the wrong end of the stick with my previous comment. Sorry!

**Comment by tomaroberts** [comment]
I think this issue needs some careful work and might be a good basis for a student project. I'm mindful the issue is being shifted from milestone to milestone, so I'm going to remove it from them for now and we can bring it back in future.

**Comment by pcw24601** [comment]
@Lucrezia-Cester, @tomaroberts  I've had a go at modelling using Option 2 above--looks promising, but I haven't done any real testing yet (and won't for at least another week). I've submitted via the linked PR if you're interested.

**Comment by tomaroberts** [comment]
Thanks Paul – sounds good. Are you intending on getting some actual T2 mapping data to compare against? Be great to see how it compares.

**Comment by pcw24601** [comment]
Great question--did you have any particular data in mind?

I'm not sure what the gold standard should be, or even if that's what we're trying to achieve with this module in Hazen. The hard-coded reference values in the routine are from NIST analysis of the samples used in the batch of analytes in our phantom, and referenced in several publications ([https://qmri.com/premium-system-phantom-batch-data/#premium-batch-1](https://qmri.com/premium-system-phantom-batch-data/#premium-batch-1)). (Aside: our measured values are consistently ~20% higher than the published ones when measuring T2 for some spheres in plate 4, at many sites and three scanner manufacturers. We've not been able to find an explanation for this.)

However, as this is a QA test, I think we should be trying to measure how well the scanner can measure the quantities needed to determine T1 or T2 relaxometry (the scanner generated T2 maps don't generally do well for short T2s). As such, if we use an external gold standard to distinguish between algorithms we risk baking in an algorithmic correction for poor scanner performance.

Instead, I think having a good theoretical model and looking at the agreement between the model and the data should drive the algorithm selection, and the difference from the NIST relaxometry value should be the QC measure of scanner performance.

**Comment by tomaroberts** [comment]
Not sure I entirely follow. From my understanding, you have the phantom which you linked to at your hospital and the scanner's T2 mapping routine doesn't give you T2 values that match the manufacturer's reference values.

I would take the imaging data from whatever T2 mapping routine the scanner uses and then supply that to your T2 Rician version, then compare both against the reference values and the values offered by the scanner. Presumably yours will be more in line with the reference values because you've taken into account Rician effects.

I'm not familiar with using default T2 mapping protocols on a scanner – an alternative would be to perform a series of spin echo scans with varying TEs and do the mapping offline in Python/Matlab whatever you prefer. Also, you can set how many averages you use this way, therefore get higher SNR if you want, and Rician noise will be less of a factor. Could even vary the averages to investigate the interplay of Rician effects and T2 values.

**Comment by pcw24601** [comment]
Thanks for the comments--I'm still figuring this out! My thinking was thus: imagine another QA test, such as slice width. This is currently calculated from an established algorithm using a phantom with crossed ramps. Suppose someone came up with an alternative algorithm to calculate slice width from the same image, which produced a slightly different answer. How could you determine which method is best? Comparing with the slice width you specified in the scanner probably isn't the best way, as if the scanner produced too thick a slice (or the phantom ramps are thicker than specified), and the new algorithm's measurements are too small, it would perform better.

For relaxometry QA, I've focussed on assessing how good the scanners hardware is at producing the measurements needed to determine T1 and T2. (Evaluating how the scanner's software processes this data is also useful, but not currently part of the Hazen relaxometry routine.) For example, one of the many factors this depends upon is B1 accuracy, and the effect of flip pulses not being exactly 180 degrees can be seen in the oscillations between even and odd refocussing pulses on the relaxometry graphs.

You're right about the built-in T2 mapping protocols; these are a multi-contrast SE sequence, typically collecting 32 echoes. This is much faster than running 32 individual SE sequences but there is some contamination from stimulated echoes. The test data in Hazen was acquired using this sequence. The problem with the reference values is that, for some of them, we've consistency between measurements made on different scanners / manufacturers (either using scanner software or off-line processing of the images) that are inconsistent with the published values. This feels like either a theoretical problem with the multi-contrast SE technique, or an issue with the phantom, rather than a hardware / software problem with the scanner.

Finally, SNR is increased in the images by spatially averaging over an ROI, rather than averaging by increasing NEX (the scans are quite long as it is). However, I don't think increasing NEX will make Rician noise less of a factor--I thought the process for averaging was: `acquire N images->reconstruct each image->average the reconstructed images`, which would not change the noise floor. If the averaging was done in k-space (before magnitude recon) it might work. Any idea what actually happens?

**Comment by pcw24601** [comment]
@Lucrezia-Cester ready for review.

**Comment by sophie22** [comment]
looks like it's been resolved with #204

**Comment by tomaroberts** [comment]
Thanks @sophie22 – we will close Issue once PR is merged in future release.
