### ISSUE TITLE
Geometric distortion out of tolerance on Sola and Vida scanners

### ISSUE THREAD

**Issue by laurencejackson** [GSTT-CSC/hazen#110]
Geometric distortion is coming out much higher than manual measurements using ImageJ.  The scanners are out-of-tolerance even with 2D distortion correction on even though images look OK and manual measurements OK.

Example image data stored under `Quality/Hazen_Issues/`
Raised on behalf of David Price.

**Comment by tomaroberts** [comment]
Fixed with PR #175. Data below from `Quality\Hazen_Issues\CCL_Siemens_Vida`:

### Rod estimates

Yellow = old centre-of-mass method
Red = 2D Gaussian fits

(Suggest opening image in new tab and zooming-in to see Rod estimates)

![Hd_SliceWidth_COR_41001_1_rod_centroids](https://user-images.githubusercontent.com/15610752/146936503-229bedcb-2e56-4f34-895e-5324201c930b.png)

### Geometric linearity/distortion values comparison

**Old method:**

![image](https://user-images.githubusercontent.com/15610752/146936861-4f768be7-5944-479a-a4b2-08adee7b5e64.png)

**2D Gaussian method:**

![image](https://user-images.githubusercontent.com/15610752/146937019-b75024f7-4a14-47d1-9e94-c1135e11bd9f.png)

As you can see, the Geometric Distortion value is now within Tolerance and is in fact much lower – 0.06 compared to 0.79 before. Error on the Linearity value has also improved.

**Comment by tomaroberts** [comment]
Closed by #175
