### ISSUE TITLE
Calculation of MTF from a slanted edge in the ACR phantom

### ISSUE THREAD

**Issue by elizaGSTT** [GSTT-CSC/hazen#135]
For the calculate the middle ramp of slice 1 should be used.

**Comment by laurencejackson** [comment]
Thanks @elizaGSTT, is this a bug report or a feature request? Could you provide more detail on this issue and provide the more information such as the below in the case of a bug report? 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Version [e.g. 0.2]

**Additional context**
Add any other context about the problem here.

**Comment by elizaGSTT** [comment]
This is a feature request. An analysis similar to the existing one done for the magNET phantom images is required for the ACR images too. A screenshot is attached to show the required calculation on slice 1 of the norm_off (image normalization is off) images. This is still under investigation on our side as we need to find the best way to analyze resolution on the horizontal direction. Should you need initial data to work with I can provide them.

<img width="388" alt="Screenshot 2021-11-05 at 08 33 02" src="https://user-images.githubusercontent.com/93722461/140482043-c656a1b2-0241-4e2c-a283-e1dbda000580.png">

**Comment by YassineAzma** [comment]
Resolved by #324
