### ISSUE TITLE
[ACR3] SNR calculation 

### ISSUE THREAD

**Issue by elizaGSTT** [GSTT-CSC/hazen#186]
For the SNR, two images, slice 6 and slice 7 are needed, each from two identical TRA_T1_NORMOFF acquisition. These are the floor sections of the phantom. For the subtraction method, subtract slice 6 from slice 7 and in the resulting image calculate the noise from a large circular 195-205mm^2 ROI in the phantom. On slice 6, use the same large ROI and find the mean pixel value. The final needed calculation is SNR = Slice 6 mean pixel value /Subtraction image ROI mean pixel value x sqrt(2). 
 
![image](https://user-images.githubusercontent.com/93722461/146511248-7c92b6a2-1dcb-44a0-a141-10bef292bac2.png)

**Comment by YassineAzma** [comment]
I'm not sure I quite understand what is being asked for here. Do you want a typical subtraction SNR (as per NEMA) from two identical acquisitions with the same slice from each dataset being involved in a subtraction? Or do you want slice 7 and slice 6 being subtracted - if so, why is a second acquisition needed? I don't think the latter would be a great idea; here's the [NEMA standard for SNR measurement](https://mriquestions.com/uploads/3/4/5/7/34572113/nema_snr_standards_2008.pdf).

**Comment by elizaGSTT** [comment]
We want the typical SNR subtraction but when using the ACR phantom to calculate it you use slice 6 and 7 which are the flood sections. I used the acr manual and we could probably do with one acquisition you’re right on that.

**Comment by YassineAzma** [comment]
I've never encountered SNR measurements using different slices in a subtraction. The typical standard, as mentioned in the NEMA link I provided above, is two identical scans and you take the same slice. I'm looking at the [ACR QC manual](https://www.acr.org/-/media/ACR/Files/Clinical-Resources/QC-Manuals/MR_QCManual.pdf) and I'm unable to find reference to this in the SNR section (pg 97). Can you elaborate? The ACR phantom guidance for analysis itself does not include reference to measurement of SNR, as that's not within the scope of the tests.

If I were to go ahead and write a script to do a subtraction of 6 and 7, it would rely on a number of assumptions:

- Noise distributions in slice 6 and 7 are directly comparable.
- B<sub>0</sub> and B<sub>1</sub> performance is identical for both slices.
- There is no partial volume - for the newer model of the ACR phantom which has a hypointense board in slice 5 rather than a grid, if the operator is sloppy with superior-inferior positioning during set-up or the scanner's slice positioning is poor, this board can be seen in Slice 6. Speaking from experience here from some of the data I have from other sites.
- The sensitivity profiles of the receiver coil elements are identical in slices 6 and 7.

I feel this method would introduce a number of confounds compared to the existing standard of simply doing the acquisition twice and using the same slice in the subtraction.

Alternatively, you could do single-image SNR (as seen in the manual above which they recommend) and perform a Rician noise correction, but I'm under the impression David Price at GSTT isn't fond of that method from the brief meeting on Teams I had with him last year.

**Comment by elizaGSTT** [comment]
I have been trying to find the source I followed but it was not an official doc it was a presentation I had found so it could as well be wrong. You’re right about the issues mentioned so I guess we could use prob slice 6 or 7 from 2 different acquisitions and calculate the SNR. Tbh I think I had tried that as well and got similar results cause I remember us taking two acquisitions and I was trying to see the outcomes with image J. Would you agree if we used slice 6 from 2 different scans and find the SNR that way and compare what we find?

**Comment by YassineAzma** [comment]
This has been resolved in PR #309 .
