### ISSUE TITLE
License Requirements for Docker Desktop

### ISSUE THREAD

**Issue by RFranklin-MR** [GSTT-CSC/hazen#200]
There has been a update (last autumn) to Docker’s terms of use/subscription model. It is my understanding (https://www.docker.com/blog/updating-product-subscriptions + https://www.docker.com/pricing/faq) that businesses with over 250 employees (such as GSTT), using Docker Desktop for commercial applications (MR Physics performing QA for external contracts with Hazen) should be paying for it.

There is a grace period in place until January 31st 2022.

**Comment by laurencejackson** [comment]
Just to bump this with @hshuaib90, @tomaroberts, and @Lucrezia-Cester.

The grace period has now expired, so unless anyone can be confident that the new license does not apply in this case we will need to change the usage instructions back to the venv version and remove the docker features. 

Happy to assign this issue to myself if there are no objections?

**Comment by hshuaib90** [comment]
I don’t think we need to make any changes, ultimately its for the end user to decide which method to use. At most we might make clear the implications of using the docker method.

**Comment by RFranklin-MR** [comment]
Can I just clarify that my understanding of the situation is correct (we can't use docker for external contracts), as we have a number of external QAs and acceptance tests from next week?

And are there up to date instructions anywhere for installing it using a venv?

**Comment by laurencejackson** [comment]
Yes, to clarify what I think Haris is suggesting. It's up to the user to decide which implementation is right for them, we can provide both since there are still some users who aren't using Hazen for commercial applications. In your case I think you will probably need to use the virtual environment version of hazen.

To set up the virtual environment implementation the installation instructions in the readme are up to date under the [Linux & MacOS heading](https://github.com/GSTT-CSC/hazen#linux--macos). However, there are currently no usage instructions current for using the venv implementation (I've opened #212 for this).

To use the venv version you just need to activate the venv and use the command `hazen` instead of `hazen-app`, everything else is the same. Let me know if any issues!

**Comment by tomaroberts** [comment]
Going to close this actually – as Haris says, it's for the user to decide on which method to use. If the licensing discussion resurfaces, then we can update documentation.
