### ISSUE TITLE
SNR putting ROIs in the wrong location

### ISSUE THREAD

**Issue by simonshah** [GSTT-CSC/hazen#233]
Running an SNR test on the data acquired on a lower field strength scanner where the SNR is a bit lower. The ROIs failed to be located in the correct places. 

![image](https://user-images.githubusercontent.com/103638799/163366031-289e6729-cd9d-41d7-adc8-186c289378c0.png)

![image](https://user-images.githubusercontent.com/103638799/163366891-344990e5-1d4c-4c05-b25d-dc914d5d6016.png)

**Comment by tomaroberts** [comment]
Hi @simonshah  – thanks for flagging this. Can you provide the data in the example so we cant test?

**Comment by RFranklin-MR** [comment]
I believe @simonshah has granted you access to the sharepoint for the offending files; if not, here are some that also hit this failure. 
[HC_COR_ND.zip](https://github.com/GSTT-CSC/hazen/files/9462787/HC_COR_ND.zip)
As this was on a 1.5T (I think) at a more recent QA clearly this issue is not restricted to low SNR scenarios. Is this a variant on https://github.com/GSTT-CSC/hazen/issues/108 rearing its head again? 
I'll gather a little more information to attempt to identify a pattern.

**Comment by RFranklin-MR** [comment]
No more information gathering needed! @laurencejackson shall I verify this issue with the 0.55T data is resolved once the PR is merged?

**Comment by laurencejackson** [comment]
@RFranklin-MR this feature is now merged, can you install Hazen from source (the pip release isn't finalised yet) and check this issue is resolved?
