### ISSUE TITLE
acr uniformity 

### ISSUE THREAD

**Issue by elizaGSTT** [GSTT-CSC/hazen#370]
@YassineAzma for uniformity it displays values in all the slices. that is an issue in the sag and coronal planes. can this be fixed so we can only see the value on slice 7? the values come out pretty low many times but not sure if that is an algorithm issue. 

<img width="868" alt="image" src="https://github.com/GSTT-CSC/hazen/assets/93722461/c9915fe0-cbba-4fc2-a56e-c2ea40d82f7e">

[](url)

**Comment by YassineAzma** [comment]
My code doesn't currently support non-axial planes.

This is a good catch though. My code is currently sorting positions based on the z-coordinate, which only varies for axial acquisitions. This will be resolved in #352.

**Comment by RFranklin-MR** [comment]
MR Physics update: occasionally we seems to encounter this issue - possibly when the phantom is slightly incorrectly oriented/positioned, that all slices of the phantom are analysed instead of the correct one. This happened also at a recent QA, and a slight adjustment seemed to address it. However, some testing has been performed with the phantom rotated in-plane, and this issue wasn't seen (so it's not necessarily clear that handling different phantom orientations will resolve this).

We will try to replicate this issue, with some intentional rotations/misalignments of the phantom, and update.

**Comment by sophie22** [comment]
I believe this issue has (largely) been resolved, output using hazen version 1.3.0 returns a value only for slice 7.
@RFranklin-MR and @elizaGSTT please confirm whether this issue is still relevant and close if not, please.

**Comment by mollybuckley** [comment]
An update on this - I spoke to some of the physics team as to whether this issue can be closed, and they said that they would like to keep it open until they've tested the code on a few more QA's.

**Comment by sophie22** [comment]
this issue is a result (symptom) of #352 and will be tackled as part of that.
